# Jekyll Configuration

# Site Settings
url: "https://notes.ayushsharma.in"
website_url: "https://notes.ayushsharma.in/"
title: ayush sharma's notes â˜• + ğŸ§ + ğŸ•¹ï¸
email: ayush@ayushsharma.in
images-path: /static/images/
videos-path: /static/videos/
js-path: /static/js/
baseurl: "" # the subpath of your site, e.g. /blog

# Post Settings
permalink: /:year/:month/:title

# Build settings
markdown: kramdown
highlighter: rouge


# Sass settings
sass:
    style: :compressed

# Collections
collections:
    collection_nav_links:
      output: false
    collection_projects:
      output: false
    collection_social:
      output: false


# Plugins
plugins:
  - jekyll-minifier